int8 X_AXIS = 0
int8 Y_AXIS = 1
int8 Z_AXIS = 2

bool STOP = 0
bool START = 1

bool status
string tf_root_frame_name
string tf_tip_frame_name
string plot_title
int8 plot_axis_x
int8 plot_axis_y
---
bool success
